server:
  affinity: ""
  ha:
    enabled: true
    replicas: 5

    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "consul" {
        path = "vault"
        address = "consul-consul-server:8500"
      }

      service_registration "kubernetes" {}

ui:
  enabled: true
  serviceType: "ClusterIP"
  externalPort: 8200

injector:
  enabled: true
  externalVaultAddr: ""
  authPath: "auth/kubernetes-kind"
