apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: ENV-OWNER-vault-backend
spec:
  provider:
    vault:
      server: "https://vault.paygo.com.br"
      path: "secrets"
      version: "v1"
      auth:
        kubernetes:
          mountPath: "CLUSTER_NAME"
          role: "ENV-OWNER-all"
          serviceAccountRef:
            name: "vault"
            namespace: "external-secrets"