apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: ENV-OWNER-vault-backend
spec:
  provider:
    vault:
      server: "https://seu-vault.com.br" # Vault adresss
      path: "secrets" #Secret engine path https://www.vaultproject.io/docs/secrets
      version: "v1" #Secret engine version (Required for secret kv type)
      auth: # Authentication in vault
        kubernetes: #Kubernetes auth type
          mountPath: "CLUSTER_NAME" #Path of kubernetes auth method https://www.vaultproject.io/docs/auth/kubernetes
          role: "ENV-OWNER-all" #kubernetes auth have role configuration
          serviceAccountRef: #Kubernetes have 3 types os auth method. This use service account
            name: "vault" #Name of Service account
            namespace: "external-secrets" #Namespace of service account