apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: ENV-OWNER-SERVICE #Name of ExternalSecret object
  namespace: "OWNER-ENV" #Namespace of ExternalSecret object
spec:
  refreshInterval: "5m" #Interval for kubernetes secret sync with vault secret
  secretStoreRef: #Configuration os SecretStore or ClusterSecretStore
    kind: ClusterSecretStore
    name: ENV-OWNER-vault-backend #Vide ClusterSecretStore.yaml
  target:
    name: SERVICE #Secret that will be created 
  dataFrom:
  - key: ENV/OWNER/SERVICE #Secret path in hashicorp vault