apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: ENV-OWNER-SERVICE
  namespace: "OWNER-ENV"
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: ENV-OWNER-vault-backend
  target:
    name: SERVICE
  dataFrom:
  - key: ENV/OWNER/SERVICE