global:
  enabled: true
  datacenter: tecktools
  gossipEncryption:
    secretName: "consul-gossip-encryption-key"
    secretKey: "key"
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
  acls:
    manageSystemACLs: true

client:
  enabled: false

server:
  replicas: 3
  bootstrapExpect: 3
  disruptionBudget:
    maxUnavailable: 0